### ISSUE TITLE
Implementation of Configuration Manager 

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#5995]
# Unit Stack Configuration Editing Requirements

There is not currently a way to add or end stack/pipe relationships. 

- Need the ability to add stack/pipe with an active date.
- Need the ability to modify stack/pipe active/retire date.
- Need the ability to connect units to a stack/pipe with an begin (effective) date.
- ~~Need the ability to modify a unit to stack/pipe connection's begin and end dates.~~
- Need the ability to modify a unit to stack/pipe connection's end date, changing a null to an actual date.

After the changes above have been made, display the following and allow the user to accept or reject the changes.

- List of locations for the monitoring plan. 
- Begin and end quarter of the monitoring plan. 
- Reporting frequency of the monitoring plan. 
- Begin and end quarter of the reporting frequency. 
- ~~Indication of whether there are submitted emissions that are no longer covered by the changed configuration.~~
- **A single monitoring plan can have multiple reporting frequencies over different quarter periods.**

Note: Right now in 2.0, users are unable to delete records and would need to revert to official and start over.  

### Interface:
- The manager should be placed on its own screen, accessed via a button on the sidebar (beneath _Monitoring Plans_).
  - This button will not be shown in the public view, i.e. the manager will only be available to logged-in users.
- There should be a section for adding/editing stack/pipes and a separate section for adding/editing unit stack configurations.

### Other considerations:

- Do not require the evaluation and submission of monitoring plans whose begin and end quarters were not affected by the configuration changes. This would include the reporting frequency quarters. **_Confirm with CAMD that it is okay to require evaluations and submittals for inactive configurations where begin and end quarters were changed_**.
- What to do with configuration changes that involve already submitted emissions data?
 
### Also Read the Following Comments

- **Configuration Management Principles**
  - Models for Adding to Working Table
  - Merge Working Table Rows
  - Updating Reporting Frequencies
- **Suggested Plants for Testing**
- **Affected and Needed Tables**

**Comment by annalbrecht** [comment]
Need screenshots from 1.0. What are the mechanics for doing the changes. Scott and Dwayne will meet to discuss further.

**Comment by djw4erg** [comment]
### Configuration Management Principles

1. **Units** (affected by a program) should **belong in an MP** for each quarter **from** the quarter of its **earliest Monitor Method**, **through** the quarter of its **retirement** based on UNIT_OP_STATUS (if it has retired).
2. A unit that has **never** been **associated with** a **stack or pipe** in the UNIT_STACK_CONFIGURATION table will only **exist in one MP** as the **sole location**.  The begin quarter of the MP will be the quarter of the earliest Monitor Method, and the end quarter will be the quarter of the unit retirement if it has retried, otherwise it will be null.
3. A unit that has been associated with stacks or pipes will have one or more MP.  These MP will contain at least one unit and one stack or pipe, but at least three locations with at least two being stacks or pipes or units (see Note 1 below).  A MP's locations are connected to each other through a web of UNIT_STACK_CONFIGURATION rows with an intersection of Begin and End Dates in quarters that match the MP Begin and End Quarters.
4. MP Reporting Frequency (MONITOR_PLAN_REPORTING_FREQ) rows indicate whether a MP reports annually (quarterly) or just for ozone season.  The reporting frequency for an MP depends on whether the affected programs at units in the MP are annual or ozone season reports.  The reporting frequency is always annual when annual programs exist.  When only ozone season programs exist, the reporting frequency is ozone season.  As the mix of annual vs ozone season programs changes for a MP, the MP can have different reporting frequencies.

**Notes**:
1. MP contain at least three locations because information is reported at a unit when it only has one stack that is not connected to other units, and has zero pipes or one pipe that is not connected to other units.  Under these conditions, the source does not include the stack or pipe as separate locations, and reports their data at the unit.

### Unit Stack Configuration Editing/Import Rules

Note that changes refer to differences compared with the Official (CAMDECMPS) USC, not the last USC saved in the Workspace (CAMDECMPSWKS).

**Updating an Existing (in Official) USC**:

1. Cannot update Begin Date
2. Cannot change an existing End Date
3. Can change a null End Date to an actual date but the date must be on or after the last day of the quarter of the last submitted emission report for the USC unit and stack/pipe.

**Adding a New USC (compared to Official)**:

1. The Begin Date must be after the quarter of the last emission report submitted for the USC unit, stack or pipe.
2. The End Date must be either null, or on or after the Begin Date.

**USC Affects on MP Notes**:

1. Changes to existing (in Official) MP should only include adding End Quarters to MP with null End Quarters.
2. The Begin Quarters for new MP (for Official) will not include quarters for which emissions have been submitted for any location in the MP.
3. The source will need to contact ECMPS Support to make any additional MP changes.

### Single Unit MP and Method Updates

1. For a single unit MP with a unit that was not associated with an earlier MP, the MP begin quarter is based on the earliest Monitor Method.  As Monitor Methods are added, deleted or updated, if the quarter of the earliest method changes, the begin quarter of the earliest MP for the unit should change if it is a single-unit MP.

### Explanatory Pseudo Implementation

**Get UNIT_STACK_CONFIGURATION (**USC**) and UNIT data to combine into Monitoring Plans**:

1. Create a temporary **Working Table** with **Unit**, **Stack-Pipe**, **Begin Year**, **Begin Quarter**, **End Year**, **End Quarter**, and **Identifier Key** columns.  _The **Identifier Key** column should contain a sequential integer value._
2. Add rows into the **Working Table** from all rows for units associated with the plant (facility) and with a Stack (Pipe) Name that begins with "C", indicating **Common Stacks or Pipes**.  _Set the begin and end years and quarters based on the USC Begin and End Dates.  The End Year and Quarter should be null if the USC End Date is null._
3. Add rows into the **Working Table** from all rows for units associated with the plant (facility) and with a Stack (Pipe) Name that begins with "M", indicating only **Multiple Stacks** since Multiple Pipes do not exist.  _Set the begin and end years and quarters based on the USC Begin and End Dates.  The End Year and Quarter should be null if the USC End Date is null._
5. Add rows into the **Working Table**  for all units for the Plant.  Set **Stack-Pipe** set to null, and **Begin Year and Quarter** to the quarter of the earliest **Begin Date** of the MONITOR_METHOD rows for the unit,  Set the **End Year and Quarter** to the quarter of the UNIT_OP_STATUS "RET" row for the unit, if it exists, otherwise set it to null.
6. Reference the comment **Models for Adding to Working Table**,which has SQL for the previous three steps.
7. Merge the rows in **Working Table** using the logic in the **Merge Working Table Rows** comment.
8. Match the **Merged Working Table** rows to existing MP on locations and begin and end quarters.  For older MP/Merged Rows matches should exist because of the restrictions on Unit Stack Configuration updates.  The rows that do not match will have one of two differences.  For one, the locations and begin quarter will match, the MP end quarter will be null, and the merged end quarter will exist.  In this end quarter of the matching MP should change to the merged end quarter.  Otherwise the merged should represent a new MP.
9. For MP that will be ended or new MP, use the logic in **Updating Reporting Frequencies** to update Reporting Frequency rows.

**Comment by djw4erg** [comment]
### Models for Adding to _Working Table_

Note that the queries should run in the following order and for a specific plant (facility) to update the **Working Table**.

**Common Stacks and Pipes**
```
select  fac.Oris_Code,
        fac.Facility_Name,
        extract( year from usc.Begin_Date ) as Begin_Year,
        extract( quarter from usc.Begin_Date ) as Begin_Quarter,
        extract( year from usc.End_Date ) as End_Year,
        extract( quarter from usc.End_Date ) as End_Quarter,
        ( stp.Stack_Name || ', ' || string_agg( unt.Unitid, ', ' order by unt.Unitid ) ) as Location_List
  from  camd.PLANT fac
        join camd.UNIT unt
          on unt.Fac_Id = fac.Fac_Id 
        join camdecmpswks.UNIT_STACK_CONFIGURATION usc 
          on usc.Unit_Id = unt.Unit_Id
        join camdecmpswks.STACK_PIPE stp
          on stp.Stack_Pipe_Id = usc.Stack_Pipe_Id
         and stp.Stack_Name like 'C%'
 where  fac.Oris_Code in ( 3, 641, 708, 994, 1356, 1893, 2866, 2876, 2878, 3407, 10307, 52130, 55284 )
 group 
    by  fac.Oris_Code,
        fac.Facility_Name,
        extract( year from usc.Begin_Date ),
        extract( quarter from usc.Begin_Date ),
        extract( year from usc.End_Date ),
        extract( quarter from usc.End_Date ),
        stp.Stack_Name
 order 
    by  Oris_Code,
        Stack_Name,
        Begin_Year,
        Begin_Quarter,
        End_Year,
        End_Quarter;
```

**Multiple Stacks (and Pipes)**
```
select  fac.Oris_Code,
        fac.Facility_Name,
        extract( year from usc.Begin_Date ) as Begin_Year,
        extract( quarter from usc.Begin_Date ) as Begin_Quarter,
        extract( year from usc.End_Date ) as End_Year,
        extract( quarter from usc.End_Date ) as End_Quarter,
        ( string_agg( stp.Stack_Name, ', ' order by stp.Stack_Name ) || unt.Unitid || ', ' ) as Location_List
  from  camd.PLANT fac
        join camd.UNIT unt
          on unt.Fac_Id = fac.Fac_Id 
        join camdecmpswks.UNIT_STACK_CONFIGURATION usc 
          on usc.Unit_Id = unt.Unit_Id
        join camdecmpswks.STACK_PIPE stp
          on stp.Stack_Pipe_Id = usc.Stack_Pipe_Id
         and stp.Stack_Name like 'M%'
 where  fac.Oris_Code in ( 3, 641, 708, 994, 1356, 1893, 2866, 2876, 2878, 3407, 10307, 52130, 55284 )
 group 
    by  fac.Oris_Code,
        fac.Facility_Name,
        extract( year from usc.Begin_Date ),
        extract( quarter from usc.Begin_Date ),
        extract( year from usc.End_Date ),
        extract( quarter from usc.End_Date ),
        unt.Unitid
 order 
    by  Oris_Code,
        Unitid,
        Begin_Year,
        Begin_Quarter,
        End_Year,
        End_Quarter;
```

**Units Alone**
```
select  lst.Oris_Code,
        lst.Facility_Name,
        extract( year from lst.Begin_Date ) as Begin_Year,
        extract( quarter from lst.Begin_Date ) as Begin_Quarter,
        extract( year from lst.End_Date ) as End_Year,
        extract( quarter from lst.End_Date ) as End_Quarter,
        lst.Location_List
  from  (
            select  fac.Oris_Code,
                    fac.Facility_Name,
                    (
                        select  max( mth.Begin_Date)
                          from  camdecmpswks.MONITOR_LOCATION loc
                                join camdecmps.MONITOR_METHOD mth
                                  on mth.Mon_Loc_Id = loc.Mon_Loc_Id
                         where  loc.Unit_Id = unt.Unit_Id
                    ) as Begin_Date,
                    (
                        select  min( uos.Begin_Date)
                          from  camd.UNIT_OP_STATUS uos
                         where  uos.Unit_Id = unt.Unit_Id
                           and  uos.Op_Status_Cd = 'RET'
                    ) as End_Date,
                    unt.Unitid as Location_List
              from  camd.PLANT fac
                    join camd.UNIT unt
                      on unt.Fac_Id = fac.Fac_Id 
             where  fac.Oris_Code in ( 3, 641, 708, 994, 1356, 1893, 2866, 2876, 2878, 3407, 10307, 52130, 55284 )
        ) lst
 order 
    by  Oris_Code,
        Location_List,
        Begin_Year,
        Begin_Quarter,
        End_Year,
        End_Quarter;
```

**Comment by djw4erg** [comment]
### Merge Working Table Rows

**Main Logic**:
```
/* pseudocode is 1 based, not 0 based. */

currentCursor := workingTable ordered by IdentifierKey
currentRecord := currentCursor.Fetch

while ( currentRecord.Exists )
    
    compareCursor := workingTable where ( IdentifierKey > currentRecord.IdentifierKey ) ordered by IdentifierKey
    compareRecord := compareCursor.Fetch
    
    mergeOccurred := false
    
    while ( compareRecord.Exists ) and ( not mergeOccurred )
        
        if ( currentRecord.Locations ∩ compareRecord.Locations ≠ Ø ) and ( currentRecord.Period ∩ compareRecord.Period ≠ Ø )
            
            { Add workingTable rows based on merge logic, which will replace the currentRecord and compareRecord rows with the next IdentifierKeys  }
            
            workingTable.Delete( compareRecord.IdentifierKey )
            workingTable.Delete( currentRecord.IdentifierKey )
            
            mergeOccurred := true
            
        else
            /* Get the next compare row if a merge did not occur. */
            compareRecord := compareCursor.Fetch
        end if
        
    end while
    
    if ( not mergeOccurred )
        /* Current was not merged so move to the next row as the current row. */
        currentRecord := currentCursor.Fetch
    else
        /* Recreate the currentCursor to account for deletions and inserts, and start with the first entry */
        currentCursor := workingTable ordered by IdentifierKey
        currentRecord := currentCursor.Fetch
    end if
    
end while
```

### Merge Logic
```
combinedLocations = currentRecord.Locations ∪ compareRecord.Locations

case
    
    when ( compareRecord.Period.Begin = currentRecord.Period.Begin ) and ( compareRecord.Period.End = currentRecord.Period.End )
        
        workingTable <= [ combinedLocations, currentRecord.Period.Begin, currentRecord.Period.End ]
    
    when ( compareRecord.Period.Begin = currentRecord.Period.Begin ) and ( compareRecord.Period.End < currentRecord.Period.End )
        
        if ( currentRecord.Locations = compareRecord.Locations )
            workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, currentRecord.Period.End ]
        else
            workingTable <= [ combinedLocations, compareRecord.Period.Begin, compareRecord.Period.End ]
            workingTable <= [ currentRecord.Locations, compareRecord.Period.End + 1, currentRecord.Period.End ]
        end if
        
    when ( compareRecord.Period.Begin = currentRecord.Period.Begin ) and ( compareRecord.Period.End > currentRecord.Period.End )
        
        if ( currentRecord.Locations = compareRecord.Locations )
            workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, compareRecord.Period.End ]
        else        
            workingTable <= [ combinedLocations, currentRecord.Period.Begin, currentRecord.Period.End ]
            workingTable <= [ compareRecord.Locations, currentRecord.Period.End + 1, compareRecord.Period.End ]
        end if
        
    when ( compareRecord.Period.Begin < currentRecord.Period.Begin ) and ( compareRecord.Period.End = currentRecord.Period.End )
        
        if ( currentRecord.Locations = compareRecord.Locations )
            workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, compareRecord.Period.End ]
        else        
            workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, currentRecord.Period.Begin - 1 ]
            workingTable <= [ combinedLocations, currentRecord.Period.Begin, currentRecord.Period.End ]
        end if
        
    when ( compareRecord.Period.Begin > currentRecord.Period.Begin ) and ( compareRecord.Period.End = currentRecord.Period.End )
        
        if ( currentRecord.Locations = compareRecord.Locations )
            workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, currentRecord.Period.End ]
        else        
            workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, compareRecord.Period.Begin - 1 ]
            workingTable <= [ combinedLocations, compareRecord.Period.Begin, compareRecord.Period.End ]
        end if
         
    
    when ( compareRecord.Period.Begin < currentRecord.Period.Begin ) and ( compareRecord.Period.End < currentRecord.Period.End )
        
        case
            when ( compareRecord.Locations = combinedLocations ) and ( currentRecord.Locations = combinedLocations )
                workingTable <= [ combinedLocations, compareRecord.Period.Begin, currentRecord.Period.End ]
            when ( compareRecord.Locations = combinedLocations )
                workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, compareRecord.Period.End ]
                workingTable <= [ currentRecord.Locations, compareRecord.Period.End + 1, currentRecord.Period.End ]
            when ( currentRecord.Locations = combinedLocations )
                workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, currentRecord.Period.Begin - 1 ]
                workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, currentRecord.Period.End ]
            else
                workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, currentRecord.Period.Begin - 1 ]
                workingTable <= [ combinedLocations, currentRecord.Period.Begin, compareRecord.Period.End ]
                workingTable <= [ currentRecord.Locations, compareRecord.Period.End + 1, currentRecord.Period.End ]
        end case
        
    when ( compareRecord.Period.Begin > currentRecord.Period.Begin ) and ( compareRecord.Period.End > currentRecord.Period.End )
        
        case
            when ( currentRecord.Locations = combinedLocations ) and ( compareRecord.Locations = combinedLocations )
                workingTable <= [ combinedLocations, currentRecord.Period.Begin, compareRecord.Period.End ]
            when ( currentRecord.Locations = combinedLocations )
                workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, currentRecord.Period.End ]
                workingTable <= [ compareRecord.Locations, currentRecord.Period.End + 1, compareRecord.Period.End ]
            when ( compareRecord.Locations = combinedLocations )
                workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, compareRecord.Period.Begin - 1 ]
                workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, compareRecord.Period.End ]
            else
                workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, compareRecord.Period.Begin - 1 ]
                workingTable <= [ combinedLocations, compareRecord.Period.Begin, currentRecord.Period.End ]
                workingTable <= [ compareRecord.Locations, currentRecord.Period.End + 1, compareRecord.Period.End ]
        end case
        
    when ( compareRecord.Period.Begin < currentRecord.Period.Begin ) and ( compareRecord.Period.End > currentRecord.Period.End )
            
        if ( compareRecord.Locations = combinedLocations )
            workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, compareRecord.Period.End ] 
        else
            workingTable <= [ compareRecord.Locations, compareRecord.Period.Begin, currentRecord.Period.Begin - 1 ]
            workingTable <= [ combinedLocations, currentRecord.Period.Begin, currentRecord.Period.End ]
            workingTable <= [ compareRecord.Locations, currentRecord.Period.End + 1, compareRecord.Period.End ]
        end if
        
    when ( compareRecord.Period.Begin > currentRecord.Period.Begin ) and ( compareRecord.Period.End < currentRecord.Period.End )
        
        if ( currentRecord.Locations = combinedLocations )
            workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, currentRecord.Period.End ] 
        else
            workingTable <= [ currentRecord.Locations, currentRecord.Period.Begin, compareRecord.Period.Begin - 1 ]
            workingTable <= [ combinedLocations, compareRecord.Period.Begin, compareRecord.Period.End ]
            workingTable <= [ currentRecord.Locations, compareRecord.Period.End + 1, currentRecord.Period.End ]
        end if
        
end case
```

**Comment by djw4erg** [comment]
### Updating Reporting Frequencies

**Existing "_Ending_" MP**

1. **Note**: the End Quarter for the MP must be null before setting an actual End Quarter value.
2. Delete any Reporting Frequency rows for the MP with a Begin Quarter after the new MP End Quarter.
3. Set the End Quarter of the latest remaining Reporting Frequency for the MP to the MP End Quarter.

**New MP Reporting Frequency Rules**

1. Whether an MP has an annual or OS reporting frequency depends on whether and when annual and OS programs are active for units in the MP.
2. The active range from the programs depends on the quarters of the Unit Program Unit Monitor Cert Begin (UMCB) Date and End Date for units in the MP.  The dates are in the CAMD.UNIT_PROGRAM table and each unit in the MP may be affected by multiple programs.
3. When an annual program is active for the lifespan of the MP, create an annual MP Reporting Frequency with the same begin and end quarters as the MP, and a Reporting Frequency Code of 'Q'.
4. When an annual program is not active during the quarter span of the MP, but an OS program is active for the lifespan of the MP, create an OS MP Reporting Frequency with the same begin and end quarters as the MP, and a Reporting Frequency Code of 'OS'..
5. When neither an annual nor ozone season program is active for part of the period that a MP is active, that period defaults to the annual frequency of 'Q'.
6. For any period were at least one annual program is active, the period will have the annual frequency of 'Q'.
7. For any period that only has ozone season programs active, the period will have the ozone season frequency 0f 'OS'.
8. Note: **The above logic differs from ECMPS 1.0**.

### Example Table

Although this example uses two units at a common stack, it could be unit program rows at a single unit, or the combinations of a number of unit program rows at a number of units.

|MP Begin|MP End|U1 UMCB|U1 End|U1 OS Ind|U2 UMCB|U2 End|U2 OS Ind|Freq 1|Freq 2|Freq 3|Notes|
| :--- | :--- | :--- | :--- | ---: | :--- | :--- | ---: | :--- | :--- | :--- | :--- |
|2022 Q1| |1/1/2022| |0|2022-01-01| |0|Q: 2022 Q1->| | | |
|2022 Q1|2023 Q3|1/1/2022| |0|2022-01-01| |0|Q: 2022 Q1- 2023 Q3| | | |
|2022 Q1| |3/31/2022| |0|2022-03-31| |0|Q: 2022 Q1->| | | |
|2022 Q1| |1/1/2022| |0|2022-04-01| |0|Q: 2022 Q1->| | | |
|2022 Q1| |4/1/2022| |0|2022-04-01| |0|Q: 2022 Q1->| | |1|
|2022 Q1| |1/1/2022| |1|2022-01-01| |1|OS: 2022 Q1->| | | |
|2022 Q1|2023 Q3|1/1/2022| |1|2022-01-01| |1|OS: 2022 Q1- 2023 Q3| | | |
|2022 Q1| |3/31/2022| |1|2022-03-31| |1|OS: 2022 Q1->| | | |
|2022 Q1| |1/1/2022| |1|2022-05-01| |1|OS: 2022 Q1->| | | |	
|2022 Q1| |4/1/2022| |1|2022-05-01| |1|Q: 2022 Q1 - 2022 Q1|OS: 2022 Q2 ->| |1|
|2022 Q2| |5/1/2022| |1|2022-07-01| |1|Q: 2022 Q1 - 2022 Q1|OS: 2022 Q2 ->| | |
|2022 Q2| |5/1/2022| |1|2022-07-01| |0|Q: 2022 Q1 - 2022 Q1|OS: 2022 Q2 - 2022 Q2|Q: 2022 Q3 ->| |
|2022 Q2| |5/1/2022| |0|2022-07-01| |1|Q: 2022 Q1 ->| | |1|
|2022 Q2| |5/1/2022| |1|2022-07-01| |0|Q: 2022 Q1 - 2022 Q1|OS: 2022 Q2 - 2022 Q3|Q: 2022 Q4 ->| |
|2022 Q1| |1/1/2022| |1|2022-09-15|2024-05-16|0|OS: 2022 Q1 - 2022 Q2	Q: 2022 Q3 - 2024 Q2|OS: 2024 Q3 ->| |
|2022 Q1| |1/1/2022| |0|2022-09-15|2024-05-16|1|Q: 2022 Q1 ->| | | |

**Notes**
1. Quarters without an active program, default to annual (Q).

**Comment by djw4erg** [comment]
## Suggested Plants for Testing

|ORIS Code|Facility Name|Facility Id|Notes|
|---:|:---|---:|:---|
|**3**|**Barry**|1|**Variety of MP**|
|641|Gulf Clean Energy Center|126|Complex Changes|
|708|Hammond|149|Complex Changes|
|994|IPL - Petersburg Generating Station|191|Complex Changes|
|**1356**|**Ghent**|272|**Problematic in ECMPS 1.0**|
|1893|Boswell Energy Center|372|Common Stack Created and Disbanded|
|2866|W H Sammis|554|Many Changes|
|2876|Kyger Creek|558|Split Common Stacks|
|2878|Bay Shore|560|Retire Common Stack and Split Unit|
|3407|Kingston|650|Complex with CS Combine|
|**6090**|**Sherburne County**|814|**Retired Unit**|
|6264|Mountaineer (1301)|860|Annual and OS Only Units|
|10307|Bellingham|1092|Common Pipe|
|52130|BP Whiting Business Unit|7699|Common Pipe (Inactive)|
|55284|Big Sandy Peaker Plant|1398|Commom Pipe Change|

**Comment by djw4erg** [comment]
## Affected and Needed Tables

### Affected

The tables exist in both the CAMDECMPS (Official) and CAMDECMPSWKS (Workspace).  The changes occur in the Workspace versions and are submitted to the Official versions.

- MONITOR_LOCATION
- MONITOR_PLAN
- MONITOR_PLAN_LOCATION
- MONITOR_PLAN_REPORTING_FREQ
- STACK_PIPE
- UNIT (In CAMD schema and not actually changed)
- UNIT_STACK_CONFIGURATION

### Needed to determine quarter range for which unit should belong to an MP

- MONITOR_METHOD
  - Used to determine the earliest quarter that a unit should belong to any MP.
  - Earliest Begin Quarter is based on the quarter of the earliest MONITOR_METHOD BEGIN_DATE.
  - Exists in both the CAMDECMPS and CAMDECMPSWKS schemas, but should use the CAMDECMPSWKS version.
- UNIT_OP_STATUS (CAMD)
  - Used to determine the latest quarter that a unit should belong to any MP.
  - Latest Begin Quarter is based is the quarter of the latest day before the UNIT_OP_STATUS BEGIN_DATE where OP_STATUS_CD equals 'RET'.

### Needed to determine the latest emission submitted quarter for a unit and stack/pipe

1. MONITOR_LOCATION (CAMDECMPS): Matched on UNIT_ID or STACK_PIPE_ID
2. MONITOR_PLAN_LOCATION (CAMDECMPS): Matched on MON_LOC_ID
3. EMISSION_EVALUATION (CAMDECMPS): Matched on MON_PLAN_ID
4. REPORTING_PERIOD (CAMDECMPSMD): Matched on RPT_PERIOD_ID and used to determine the latest quarter.

**Comment by djw4erg** [comment]
## Adding MP for Units without an MP

1. Add section to Configuration Management to display units that are not currently in a MP.
2. Allow the user to select from these units to create MP and set the anticipated begin quarter for the MP.
3. Saving the created MP should result in the creation of the following:
   - MONITOR_PLAN row including a BEGIN_RPT_PERIOD_ID corresponding to the anticipated begin quarter.
   - MONITOR_PLAN_LOCATION row with the MON_PLAN_ID for the created MONITOR_PLAN row, and MON_LOC_ID for the unit.

**Comment by esaber76** [comment]
1. Receiving a forbidden resource error in the Change Summary window when attempting to add an MP for a unit that never submitted an MP (occurs after selecting the "+" icon and Save button).
2. Issues when ending an existing stack/pipe and USC records:
- For annual reporters, the Change Summary window shows Reporting Frequency as Ozone Season for the new and ended plans (MONITOR_PLAN_REPORTING_FREQ is correct though).
- Userid and update_date columns in CAMDECMPSWKS.STACK_PIPE not updated when ending a stack/pipe.
- Userid and update_date columns in CAMDECMPSWKS.MONITOR_PLAN_REPORTING_FREQ not updated for ended mon_plan_id when ending a stack/pipe.
- Ending a stack/pipe configuration will set this MP to Inactive, needs evaluation and submission, but there is no way to select this configuration for evaluation/submission. In ECMPS 1.0, we forced users to first submit the ended MP before being able to submit the new MP. 
- Revert to Official issues:
    - When all changes are completed in the UI, forbidden resource errors are returned for the active and inactive MP's. The new MP is removed from the database on revert though. The forbidden resource issue on the inactive MP appears to leave some changes still active in the MONITOR_PLAN, STACK_PIPE, and MONITOR_PLAN_REPORTING_FREQ tables. I also end up with an active row in the USER_CHECK_OUT table.
    - When the changes are completed via import from json file, I can revert the inactive MP, but this results in null Configuration rows when viewing the Select Configurations screen. Opening one of these null rows and selecting the tab results in an odd "Cannot read properties of null (reading '1')" error. The new MP's that were created are also not deleted from the MONITOR_PLAN and MONITOR_PLAN_REPORTING_FREQ tables. Also end up with the USER_CHECK_OUT issue.
    - The revert to official forbidden resource issue also affects other inactive configurations where no changes have been made (stack/pipe configurations and single unit configurations).  
- Cannot evaluate new MP's that are created either. The needs_eval_flg always remains Y after performing an evaluation. This blocks submission testing.
- Cannot update begin dates for existing stack/pipe and USC records logic on import:
    - The message doesn't make sense and refers to begin dates cannot be on or before end dates of the last Emission Evaluation. They will always be on or before the end date of the last Emission Evaluation. Change it to, "The Begin Date for one or more Stack/Pipe and/or Unit Stack Configuration records does not match the last official submission record for this monitoring plan. Please contact ECMPS Support if you need to correct the Begin Date for any Stack/Pipe and/or Unit Stack Configuration records."
    - When changing the begin date for an existing stack/pipe record and importing the file, a successful import message is returned (even though the backend data does not change). They should get the message above instead.
- There is logic to not allow the end date of an USC record to be before the last day of the quarter for the latest Emission Evaluation, but not for stack/pipe records. I think it would make sense to add the same logic for stack/pipe records. Would need to update this message to also include "Stack/Pipe".
3. Issues adding new stack/pipe configurations:
- ORIS 544, 11 and 12. Attempted to add new CP and associated USC records effective 10/01/2023. Receive odd "Cannot read properties of null (reading 'id')" error in the Change Summary screen. I was able to add a CP configuration for the example below so not really sure what the difference between the two is other than annual vs. ozone season reporters, but it would be good to know in case further targeted testing is needed.
- ORIS 542, 10 and 11. I was able to add a new CP configuration effective 10/01/2023.
    - When the new stack/pipe and USC records are added, update_date was also set in the STACK_PIPE, UNIT_STACK_CONFIGURATION, and MONITOR_PLAN_REPORTING_FREQ tables. This should be null unless another change occurred after the initial save. For MONITOR_PLAN_REPORTING_FREQ, update_date is also not updated for the ended mon_plan_id's.
    - Same revert issues as documented above.
    - Same evaluation issues as documented above.
- Able to successfully save new stack/pipe and USC records that have end dates before the begin dates.
4. Able to attempt to create new monitoring plans for retired, cancelled, and long-term cold storage units that never submitted a monitoring plan. Example for retired units: ORIS 544, 3, 4A, 4B, 5A, 5B, and 6. All these units retired pre-ECMPS 1.0. Example for cancelled units: ORIS 1552, 3, 4, and 5. Example for long-term cold storage: ORIS 569, EB13 and EB14. Limit this ability to only units with an active op_status_cd equal to OPR or FUT.
5. #6339 was temporarily merged to dev and this broke the Configuration Manager. Per @maxdiebold-erg, the same endpoint is used. Updates need to be made to handle this. An odd error referencing "Cannot read properties of undefined (reading 'newPlans')" was also returned when this occurred.
6. Add checks to prevent duplicate stack/pipe and USC records in UI  and via import. MONLOC-106 (stack/pipe) and MONLOC-107 (USC) screen checks prevent this in 1.0. We can use something similar. 
7. Ticket #xxxx created for future consideration to update the message returned when attempting to import new stack/pipe and USC records from a json file. ECMPS 1.0 does the same thing but a better message could be returned to help avoid ECMPS Support tickets.
8. Ticket #xxxx created to force ended monitoring plans to be submitted before new monitoring plans can be submitted.

**Comment by maxdiebold-erg** [comment]
The following 5 Pull Requests have been opened to address the changes noted [above](https://github.com/US-EPA-CAMD/easey-ui/issues/5995#issuecomment-2383544288):
- https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/586
- https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1495
- https://github.com/US-EPA-CAMD/easey-db-scripts/pull/58
- https://github.com/US-EPA-CAMD/easey-facilities-api/pull/193
- https://github.com/US-EPA-CAMD/easey-camd-services/pull/274

**Comment by esaber76** [comment]
Per 10/11/2024 standup, hide the Configuration Management module in all environments except dev and tst. #6425 created in Sprint 12 to address the remaining issues after the last round of testing.

**Comment by maxdiebold-erg** [comment]
The [above comment](https://github.com/US-EPA-CAMD/easey-ui/issues/5995#issuecomment-2407872953) has been addressed in https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1496.

**Comment by mark-hayward-erg** [comment]
@esaber76 please confirm that the configuration management appears correctly in dev.  If so, move this ticket to QA Done.

**Comment by esaber76** [comment]
Confirmed Configuration Management still showing in dev and test, but not perf. Moving this ticket to Sprint 12 to undo these particular changes once #6425 is completed.

**Comment by djw4erg** [comment]
## Note

**May update the findings below based on additional research for USC that began after 1993.**

## USC with Begin Dates Before 1993

The following were found for the 24 Unit Stack Configuration (USC) rows with Begin Dates before 1993,

- 15 matched on the USC End Date and MP End Quarter for an MP containing the the unit in the USC.
- 9 USC ended before an MP for the unit in the USC. 
  - 2 USC that began and ended in Q1 of 1963.
  - 2 USC that ended before the first MP for the unit began.
  - 5 USC ended before an MP that was not the **first** MP for the unit.

Based on this the following should be applied for USC with Begin Dates before 1993.

1. Exclude the USC if the USC has an **End Date** before 1993.
2. Exclude the USC if the USC has an **End Date** that is before the earliest MP **Begin Quarter** containing the unit in the USC.
3. Otherwise, match the USC based only on the **End Date** not both its Begin and End date.
   - @maxdiebold-erg,  **this my require a little more discussion.**

### USC and MP Data

| ORIS | Unit | MP Locations | MP Status | USC Begin | USC End | MP Begin | MP End |
| :--- | :--- | :--- | :--: | :--: | :--: | :--: | :--: |
| **544** | **7** | **CS0001, 7, 8** | **Match** | **1972 Q1** | **2007 Q4** | **1995 Q1** | **2007 Q4** |
| **544** | **8** | **CS0001, 7, 8** | **Match** | **1972 Q1** | **2007 Q4** | **1995 Q1** | **2007 Q4** |
| **2549** | **63** | **CS0002, 63, 64, 65, 66** | **Match** | **1957 Q2** | **2007 Q2** | **1995 Q1** | **2007 Q2** |
| **2549** | **64** | **CS0002, 63, 64, 65, 66** | **Match** | **1957 Q2** | **2007 Q2** | **1995 Q1** | **2007 Q2** |
| **2549** | **65** | **CS0002, 63, 64, 65, 66** | **Match** | **1957 Q2** | **2007 Q2** | **1995 Q1** | **2007 Q2** |
| 2549 | 65 | 65 | Ended | 1957 Q2 | 2007 Q2 | 2007 Q3 | 2007 Q4 |
| **2549** | **66** | **CS0002, 63, 64, 65, 66** | **Match** | **1957 Q2** | **2007 Q2** | **1995 Q1** | **2007 Q2** |
| 2549 | 66 | 66 | Ended | 1957 Q2 | 2007 Q2 | 2007 Q3 | 2007 Q4 |
| **3148** | **1** | **CS102, 1, 2** | **Match** | **1954 Q3** | **** | **1993 Q4** | **** |
| **3148** | **2** | **CS102, 1, 2** | **Match** | **1954 Q3** | **** | **1993 Q4** | **** |
| **10025** | **1E** | **CS1E1F, 1E, 1F** | **Match** | **1947 Q1** | **2007 Q2** | **1999 Q2** | **2007 Q2** |
| **10025** | **1F** | **CS1E1F, 1E, 1F** | **Match** | **1947 Q1** | **2007 Q2** | **1999 Q2** | **2007 Q2** |
| 10244 | B001 | B001 | Ended | 1963 Q1 | 1963 Q1 | 2003 Q1 | 2005 Q3 |
| 10244 | B002 | B002 | Ended | 1963 Q1 | 1963 Q1 | 2003 Q2 |  |
| 52007 | 1 | 1 | Ended | 1992 Q4 | 1999 Q1 | 2003 Q2 |  |
| 52007 | 2 | 2 | Ended | 1992 Q4 | 1999 Q1 | 2003 Q2 |  |
| **54041** | **011854** | **MS1A, MS1B, 011854** | **Match** | **1992 Q4** | **2001 Q4** | **1999 Q2** | **2001 Q4** |
| 54041 | 011854 | 011854 | Ended | 1992 Q4 | 2001 Q4 | 2002 Q1 |  |
| **54041** | **011855** | **MS2A, MS2B, 011855** | **Match** | **1992 Q4** | **2001 Q4** | **1999 Q2** | **2001 Q4** |
| 54041 | 011855 | 011855 | Ended | 1992 Q4 | 2001 Q4 | 2002 Q1 |  |
| **54041** | **011856** | **MS3A, MS3B, 011856** | **Match** | **1992 Q4** | **2001 Q4** | **1999 Q2** | **2001 Q4** |
| 54041 | 011856 | 011856 | Ended | 1992 Q4 | 2001 Q4 | 2002 Q1 |  |
| **880066** | **02** | **CS-1, 02, 03** | **Match** | **1976 Q2** | **** | **2003 Q2** | **** |
| **880066** | **03** | **CS-1, 02, 03** | **Match** | **1976 Q2** | **** | **2003 Q2** | **** |

### Query

```
select  distinct
        fac.Oris_Code,
        fac.Facility_Name,
        unt.Unitid as Unit_Name,
        (
            select  string_agg( coalesce( unt.Unitid, stp.Stack_Name ), ', ' order by stp.Stack_Name, unt.Unitid )
              from  camdecmps.MONITOR_PLAN_LOCATION mpl
                    join camdecmps.MONITOR_LOCATION loc on loc.Mon_Loc_Id = mpl.Mon_Loc_Id
                    left join camd.UNIT unt on unt.Unit_Id = loc.Unit_Id
                    left join camdecmps.STACK_PIPE stp on stp.Stack_Pipe_Id = loc.Stack_Pipe_Id
             where  mpl.Mon_Plan_Id = pln.Mon_Plan_Id
        ) as Locations,
        case
            when usc.End_Date is null and pln.End_Rpt_Period_Id is null then 0
            when ( extract( year from usc.End_Date ) = pre.Calendar_Year ) and ( floor( ( extract( month from usc.End_Date ) - 1 ) / 3 + 1 ) = pre.Quarter ) then 0
            when usc.End_Date is not null and usc.End_Date < prb.Begin_Date then 2
            else 1
        end as Match_Ind,
        case
            when usc.End_Date is null and pln.End_Rpt_Period_Id is null then 'Match'
            when ( extract( year from usc.End_Date ) = pre.Calendar_Year ) and ( floor( ( extract( month from usc.End_Date ) - 1 ) / 3 + 1 ) = pre.Quarter ) then 'Match'
            when usc.End_Date is not null and usc.End_Date < prb.Begin_Date then 'Ended'
            else 'No Match'
        end as Match_Label,
        usc.Begin_Date,
        usc.End_Date,
        prb.Period_Abbreviation as Begin_Quarter,
        pre.Period_Abbreviation as End_Quarter,
        ( extract( year from usc.Begin_Date ) || ' Q' || floor( ( extract( month from usc.Begin_Date ) - 1 ) / 3 + 1 ) ) as Usc_Begin_Quarter,
        case when usc.End_Date is not null then ( extract( year from usc.End_Date ) || ' Q' || floor( ( extract( month from usc.End_Date ) - 1 ) / 3 + 1 ) ) end as Usc_End_Quarter
  from  camdecmps.UNIT_STACK_CONFIGURATION usc
        join camd.UNIT unt on unt.Unit_Id = usc.Unit_Id
        join camdecmps.MONITOR_LOCATION loc on loc.Unit_Id = usc.Unit_Id or loc.Stack_Pipe_Id = usc.Stack_Pipe_Id
        join camdecmps.MONITOR_PLAN_LOCATION mpl on mpl.Mon_Loc_Id = loc.Mon_Loc_Id
        join camdecmps.MONITOR_PLAN pln on pln.Mon_Plan_Id = mpl.Mon_Plan_Id
        join camd.PLANT fac on fac.Fac_Id = pln.Fac_Id
        join camdecmpsmd.REPORTING_PERIOD prb on prb.Rpt_Period_Id = pln.Begin_Rpt_Period_Id
        left join camdecmpsmd.REPORTING_PERIOD pre on pre.Rpt_Period_Id = pln.End_Rpt_Period_Id
 where  usc.Begin_Date < to_date( '1993-01-01', 'yyyy-mm-dd' )
 order
    by  Oris_Code,
        Unit_Name,
        Match_Ind,
        Begin_Quarter,
        Locations
```

**Comment by djw4erg** [comment]
## Handling USC vs MP Mismatches

1. Do not attempt to match any **Calculated MP** (from USC) that **end before 2009** with an **Actual MP**.
   - These USC existed before ECMPS 1.0 was fully implemented.
2. Match any **Calculated MP** that **began before 2009** but **ended in or after 2009** with an **Actual MP** that **began before 2009** and **ended the same quarter** as the **Calculated MP**.
   1. If a match on **ended quarter** does not exist, then on the assumption that the **Calculated MP** was ended in the Workspace, match on an **Actual MP** that **does not have an end quarter**.
   2. Although it should not happen, this should produce an error if a match on more than one Actual MP occurs for either the **Actual MP** with and end date or without an end date.
3. Match any **Calculated MP** that **began before 2009** but **does not have an end quarter** with an **Actual MP** that **began before 2009** and **does not have an end quarter**.
   - Although it should not happen, this should produce an error if a match on more than one Actual MP occurs.

**Comment by annalbrecht** [comment]
Further work will be tracked on #6425.
