### ISSUE TITLE
Improve Email Sending Architecture, Async Processing and Email Per Recipient

### ISSUE THREAD

**Issue by yonatan-dp** [US-EPA-CAMD/PI-1#6885]
### Description

1. **Synchronous Email Sending in API Endpoints**: The `/queue` and `/process` endpoints currently wait for email sending to complete before
returning API results, causing unnecessary delays (especially email sending fails and retry is triggered). These endpoints should send emails asynchronously (fire and forget pattern) and return their results without waiting for email sending completion.

2. **Bulk Recipient Handling**: Throughout easey-camd-services, emails are currently sent to all recipients in a single request by passing
comma-separated values to the `toEmail` field. This approach can trigger spam filters and cause email rejections by strict email servers. Each
recipient should receive an individual email. This needs to be fixed centrally in one location, ideally where the actual email sending occurs. 

3. **Email Footer Standardization**: All email templates in easey-content should have standardized `to` and `from` information at the bottom (see dev/templates/submission-151.html in easey-content).  This means, camd-services should assume all templates have these footer and should consistently replace the 'to' and 'from' placeholders when sending email based on templates (partially implemented as part of ticket #6610, needs validation for universal application).

Affected services include:
- Mail template service
- Submission email service
- All other email-sending services in easey-camd-services

### Acceptance Criteria

- [ ] Implement asynchronous email sending for `/queue` and `/process` endpoints (fire and forget pattern)
- [ ] Create a centralized email splitting mechanism that processes comma-separated recipient lists in the toEmail field.
- [ ] Verify all email templates include `to` and `from` placeholders at the bottom
- [ ] Ensure the service replaces `to` and `from` placeholders in all emails

**Comment by yonatan-dp** [comment]
The development for this ticket was completed together with #6886 
See PRs linked to #6886.

**Comment by lgiannini1** [comment]
Tested in dev:

- [ ] Create a centralized email splitting mechanism that processes comma-separated recipient lists in the toEmail field.
     - [ ] Submission Email
          - **Issue**: Submission emails still sent with a CC list
          - <img width="645" height="475" alt="Image" src="https://github.com/user-attachments/assets/b0d380f2-39ea-4c1f-8d5b-01b07a51cdbd" />
     - [ ] Submission Window Opened
          - **Issue**: Only one Submission Window Open email is sent to the recipients in the "To:" field instead of send one email per recipient
          - <img width="906" height="467" alt="Image" src="https://github.com/user-attachments/assets/507061af-1be2-4d2c-9d31-0c2fc602c600" /> 
     - [x] Submission Reminder
          - One email is sent per recipient
     - [x] Submission Critical Error Reminder
          - One email is sent per recipient
     - [ ] Resubmission Window Closed
          - Only one Resubmission Window Closed email is sent to the recipients in the "To:" field instead of send one email per recipient
          - <img width="901" height="472" alt="Image" src="https://github.com/user-attachments/assets/134cece3-fd60-4b92-b79e-f3c6aed53897" />
- [x] Verify all email templates include to and from placeholders at the bottom
     - [x] Submission Email
     - [x] Submission Failure
     - [x] Submission Window Opened
     - [x] Submission Reminder
     - [x] Submission Critical Error Reminder
     - [x] Resubmission Window Closed
- [ ] Ensure the service replaces to and from placeholders in all emails
     - [ ] Submission Email
          - Submission emails do not contain  a list of all recipients in the body. 
          - Email from dev:
          - <img width="897" height="492" alt="Image" src="https://github.com/user-attachments/assets/9aef5409-116c-4402-9f24-aa1b266c2d89" />
          - Email from test:
          - <img width="890" height="495" alt="Image" src="https://github.com/user-attachments/assets/def1917e-72bd-4e95-97d7-484983d62c62" />
     - [ ] Submission Window Opened
          -  **Issue**: All recipients are listed in the body of the email, but the email addresses are not displayed. See screenshot above.
     - [ ] Submission Reminder
          - **Issue**: Email address is not displayed for recipients, just the name
          - <img width="898" height="475" alt="Image" src="https://github.com/user-attachments/assets/4fecd8cc-46f1-476e-ad50-2f44378c5821" />
     - [ ] Submission Critical Error Reminder
          -  **Issue**: Email address is not displayed for recipients, just the name
          -   <img width="893" height="475" alt="Image" src="https://github.com/user-attachments/assets/c4bd2935-9cb2-4b69-82e4-5a7f0cbcee4d" />

     - [ ] Resubmission Window Closed 
          -  **Issue**: All recipients are listed in the body of the email, but the email addresses are not displayed. See screenshot above. Also, the names are in a different format than the submission reminder emails. Is there a reason for this?

**Comment by yonatan-dp** [comment]
@lgiannini1 
On your question: `Should the CC list still appear in these emails?`

- I don't know if any requirement changed on that from what was implemented a while back. This ticket only updated the email sending architecture (not individual email sending logic, such as Submission Emails).  So, perhaps check with Mark or Scott and if that needs to be changed, it is a separate ticket specific to submission emails.

**Comment by lgiannini1** [comment]
@ergjustin 

- The Window Notification emails (Emissions Submission Window Open and Resubmission Window Closed emails) and Submission Reminder emails still aren't displaying the email address for the receipients in the "To:" section.
     - <img width="926" height="455" alt="Image" src="https://github.com/user-attachments/assets/04e42946-1c72-453c-bcf8-1b3bf53d8580" />
     - <img width="928" height="468" alt="Image" src="https://github.com/user-attachments/assets/3983da21-f21b-4f14-96ba-219dee646fe0" />
     - <img width="911" height="504" alt="Image" src="https://github.com/user-attachments/assets/833df2f6-e939-43e4-adc0-b150a4d08859" />
     - <img width="924" height="479" alt="Image" src="https://github.com/user-attachments/assets/82ff315c-8f98-4a49-b2da-53ac68165aee" />
 - <img width="930" height="492" alt="Image" src="https://github.com/user-attachments/assets/7016e741-6ca7-4af7-ac63-c0ec78bc6a34" />

- The CC list is removed from the submission feedback emails, but one email is sent to my email and then one email is sent to CAMD_BP_3.1 including all the other recipients. Also, there appears to be a formatting issue with the list of recipients in the "To:" section.
     - <img width="910" height="506" alt="Image" src="https://github.com/user-attachments/assets/6771df89-9a13-4d28-8b46-b2da155512e9" />
     - One email is also sent for Submission Window Open and Emissions Resubmission Window Closed emails
          - One email sent for the four recipients
          - <img width="930" height="492" alt="Image" src="https://github.com/user-attachments/assets/8ee02a03-2ce7-463e-a4c1-76b753ae9aac" />
          - One email sent for the two recipients
          - <img width="931" height="458" alt="Image" src="https://github.com/user-attachments/assets/98998131-f7fc-48cf-928e-066c5d98e456" />

**Comment by lgiannini1** [comment]
@ergjustin It still looks like the same issue in my previous comment are occurring on dev. There is a formatting issue in the submission feedback emails, and the recipient email addresses aren't included for window notification/ submission reminder emails

Submission emails:
<img width="642" height="264" alt="Image" src="https://github.com/user-attachments/assets/7c8191df-6ae6-44f7-a9e9-674ad2e0d60c" />

Submission Reminder:

<img width="894" height="484" alt="Image" src="https://github.com/user-attachments/assets/8f5f90b4-2e88-4906-bdc1-525c4c74cb49" />

Window Notification:

<img width="906" height="459" alt="Image" src="https://github.com/user-attachments/assets/51fa05ab-036e-4015-9dd8-b945a62898f1" />

The recipient list is also included in the bottom of the submission feedback report files. Example file: [7697_SUBMISSION_FEEDBACK.html](https://github.com/user-attachments/files/23344639/7697_SUBMISSION_FEEDBACK.html)

<img width="1904" height="533" alt="Image" src="https://github.com/user-attachments/assets/cff78785-c2c2-44ad-9864-53af8cad1614" />

MATS Submission feedback emails also have a CC list similar to how the submission emails did, and the full list of recipients is not included in the body.

<img width="651" height="483" alt="Image" src="https://github.com/user-attachments/assets/59c4aa2f-c850-4d8e-b47d-d6dc3c14f493" />

**Comment by ergjustin** [comment]
@lgiannini1 
In the Submission emails, the body of the first email contains the submitter’s email, and the remaining emails are from the recipient list.

@mark-hayward-erg 
For the Submission Reminder and Window Notification emails, it’s showing user IDs instead of emails ,not sure why. It might be related to the EmailGroupingStrategies logic. I’m not very familiar with .NET, so it would be great if someone with more .NET experience could take a look.

I’ll continue checking the Submission Feedback Report files issue and the Mats email issue.

Note: If no response is found for emailRecipientList in the local environment, use the JSON response below.

[example_email_recipient_list.json](https://github.com/user-attachments/files/23363400/example_email_recipient_list.json)

**Comment by ergjustin** [comment]
**Note**:
In some emails, the user ID may appear as a placeholder in the “To” field. Clicking the user ID will reveal the full email address.

<img width="1354" height="469" alt="Image" src="https://github.com/user-attachments/assets/950e0760-8150-4ef3-89f7-332bb652c398" />

**Comment by yonatan-dp** [comment]
@lgiannini1 I have fixed the the issue where user IDs are displayed instead of email address for Submission Reminder and Window Notification emails.   **Change has been deployed to Dev.**

### Before the change

<img width="654" height="364" alt="Image" src="https://github.com/user-attachments/assets/aedef93c-6e94-498d-81e9-4524c3ad0fa6" />

### After the Change

<img width="694" height="569" alt="Image" src="https://github.com/user-attachments/assets/94d06ddc-5f73-4776-9cfe-282011d17d65" />

<img width="645" height="388" alt="Image" src="https://github.com/user-attachments/assets/360fc775-ff19-46cd-bab6-3fb28de721dc" />


**You can retest now as the above changes have now been deployed to Dev**

**Comment by lgiannini1** [comment]
- [ ] Submission Feedback Emails
     -  Recipients are displayed correctly
     - One email sent per recipient
     - @ergjustin Submission Feedback Report Attachments still have the "To" and "From" emails in the footer.
     <img width="1939" height="536" alt="Image" src="https://github.com/user-attachments/assets/12a9e89b-1357-490f-b48e-d8c803f88249" />

- [ ] MATS Submission Feedback
     -  One email sent per recipient
     - @ergjustin The recipient names are all lowercase
     <img width="900" height="495" alt="Image" src="https://github.com/user-attachments/assets/8ed982ef-cb24-4bcd-8dca-65c655b8badb" />

- [x] Submission Window Opened
     -  Recipients are displayed correctly
     - One email sent per recipient
- [x] Resubmission Window Closed
     -  Recipients are displayed correctly
     - One email sent per recipient
- [x] Submission Reminder
     - Recipients are displayed correctly 
     - One email sent per recipient
- [x] Submission Reminder Critical Errors
     - Recipients are displayed correctly 
     - One email sent per recipient
- [x] Outstanding Emissions Submission Reminder
     - Recipients are displayed correctly
     - One email sent per recipient

**Comment by ergjustin** [comment]
Remove  "To" and "From" Submission Feedback Emails in the footer : 
Dev env: https://github.com/US-EPA-CAMD/easey-content/pull/372
Release: https://github.com/US-EPA-CAMD/easey-content/pull/373

MATS Submission Feedback: The recipient names are all lowercase
Dev env : https://github.com/US-EPA-CAMD/easey-camd-services/pull/701
Release : https://github.com/US-EPA-CAMD/easey-camd-services/pull/702

**Comment by maheese** [comment]
Confirmed by reviewing associated pull requests.
